// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5B0vqDqq-sQ32W3gzvTKfXvWLl0z5MJw',
    appId: '1:1088560191949:web:8824aea70ce64af3778c84',
    messagingSenderId: '1088560191949',
    projectId: 'smarty-entregas-c3415',
    authDomain: 'smarty-entregas-c3415.firebaseapp.com',
    storageBucket: 'smarty-entregas-c3415.firebasestorage.app',
    measurementId: 'G-SFNNDY8R5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwC0xh2ab1hj8MWW_NCxPW-nnptOerVqc',
    appId: '1:1088560191949:android:7cfe0149079f8808778c84',
    messagingSenderId: '1088560191949',
    projectId: 'smarty-entregas-c3415',
    storageBucket: 'smarty-entregas-c3415.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDix39BWqTeOIFEFKT6Ug8xFfmj7T_kIeE',
    appId: '1:1088560191949:ios:1358933c24c73232778c84',
    messagingSenderId: '1088560191949',
    projectId: 'smarty-entregas-c3415',
    storageBucket: 'smarty-entregas-c3415.firebasestorage.app',
    iosBundleId: 'com.example.smartyEntregas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDix39BWqTeOIFEFKT6Ug8xFfmj7T_kIeE',
    appId: '1:1088560191949:ios:1358933c24c73232778c84',
    messagingSenderId: '1088560191949',
    projectId: 'smarty-entregas-c3415',
    storageBucket: 'smarty-entregas-c3415.firebasestorage.app',
    iosBundleId: 'com.example.smartyEntregas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5B0vqDqq-sQ32W3gzvTKfXvWLl0z5MJw',
    appId: '1:1088560191949:web:72b3253aa74b09bb778c84',
    messagingSenderId: '1088560191949',
    projectId: 'smarty-entregas-c3415',
    authDomain: 'smarty-entregas-c3415.firebaseapp.com',
    storageBucket: 'smarty-entregas-c3415.firebasestorage.app',
    measurementId: 'G-6N6QQNSW9P',
  );
}
